name:                HaskellHacking
version:             0.1.0.0
github:              "githubuser/HaskellHacking"
license:             BSD3
author:              "Daniel Latham"
maintainer:          "daniellatham11@gmail.com"
copyright:           "2018 Daniel latham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/drlatham/HaskellHacking#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- containers

library:
  source-dirs: src

executables:
  HaskellHacking-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellHacking

tests:
  HaskellHacking-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellHacking
